services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: vtreview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vtindex@123
    ports:
      - "5432:5432"
    volumes:
      - vtreview_postgres:/var/lib/postgresql/data

volumes:
  vtreview_postgres:
