# Generated by Django 5.2.13 on 2026-09-17 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_users', to='api.role'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE auth_user ADD COLUMN IF NOT EXISTS role_id bigint REFERENCES role(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
            ALTER TABLE auth_user DROP COLUMN IF EXISTS role_id;
            """,
        ),
    ]

