# Generated by Django 5.2.13 on 2026-09-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
