# Generated by Django 5.2.13 on 2026-09-17 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_address_company_address_type_company_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_company_name', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('subsidiary', 'Subsidiary'), ('affiliate', 'Affiliate'), ('brand', 'Brand')], default='affiliate', max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='api.company')),
                ('related_company', models.ForeignKey(blank=True, db_column='related_company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_companies', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'Related Companies',
                'db_table': 'related_companies',
                'ordering': ['company', 'relationship_type', 'related_company_name'],
            },
        ),
    ]
